Feature: Generate right 

  As a user
  I want to test some site functionality
  So that I can be sure that generate function works correctly

@tag1
Scenario Outline: Check that site language changed to ru
	Given User opens <homePage> page
	When User change language to ru
	Then User checks that home page display keyword <keyword>

	Examples:
    | homePage                | keyword |
    | https://www.lipsum.com/ | рыба    |

@tag2
Scenario Outline: Check that generate button works
	Given User opens <homePage> page
	When User press in generate button
	Then User checks that first paragraph on generate result page contains<keywords>
	Examples:
    | homePage                | keywords                                                |
    | https://www.lipsum.com/ |Lorem ipsum dolor sit amet, consectetur adipiscing elit|
@tag3
Scenario Outline: Check that generate correct size of words
	Given User opens <homePage> page
	When User choose words in radio buton
	And User put amount <amount> in input field
	And User press in generate button
	Then User checks that amount of generated words are <amount>

	Examples:
    | homePage                | amount |
    | https://www.lipsum.com/ |   10   |
	| https://www.lipsum.com/ |   5    |
	| https://www.lipsum.com/ |   20   |
	| https://www.lipsum.com/ |   0   |
	| https://www.lipsum.com/ |   -1   |
@tag4
Scenario Outline: Check that generate correct size of bytes
	Given User opens <homePage> page
	When User choose bytes in radio buton
	And User put amount <amount> in input field
	And User press in generate button
	Then User checks that amount of generated bytes are <amount>
	Examples:
    | homePage                | amount |
    | https://www.lipsum.com/ |   41   |
	| https://www.lipsum.com/ |   10    |
	| https://www.lipsum.com/ |   100   |
@tag5
Scenario Outline: Check that checkbox works
	Given User opens <homePage> page
	When User check out checkbox
	And User press in generate button
	Then User checks that first paragraph does not begin with <keywords>
	Examples:
    | homePage                | keywords    |
    | https://www.lipsum.com/ |Lorem ipsum|

@tag6
Scenario Outline: Check that random generated text in paragraphs contains keyword
	Given User opens <homePage> page
	When User press in generate button
	Then User checks that amount of <keyword> in paragraphs from <homePage> on generate result page not more that <amount>.
	Examples:
    | homePage                | keyword | amount |
    | https://www.lipsum.com/ | lorem   | 3      |
